server:
  port: 9191

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true


jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY

  hystrix:
    command:
      fallbackcmd:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 4000