server:
  port: 9006

spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/microservices-1-db
zipkin:
  base-url: http://127.0.0.1:9411/

jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
  expiration: 86400